# sonar-project.properties
sonar.projectKey=anna-shustser_8.2CDevSecOps
sonar.organization=anna-shustser
sonar.host.url=https://sonarcloud.io
sonar.login=${JenkinsToken}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Go